
sudo: required
services:
  - docker

before_install:
  - docker build -t mikewilson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mikewilson/docker-react npm run test -- --coverage